build: false
clone_folder: c:\projects\padawan

cache:
    - composer.phar

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1

install:
    - IF EXIST c:\tools\php (SET PHP=0)
    - IF %PHP%==1 cinst -y OpenSSL.Light
    - IF %PHP%==1 cinst -y php
    - cd c:\tools\php
    - IF %PHP%==1 copy php.ini-production php.ini /Y
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd c:\projects\padawan
    - IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/download/1.3.0/composer.phar)
    - php composer.phar install --prefer-dist --no-progress

test_script:
    - cd c:\projects\padawan
    - SET X=0
    - php bin/peridot specs || SET X=!errorlevel!
    - php bin/behat || SET X=!errorlevel!
    - exit %X%
